@startuml
title Отправка сообщения

actor Пользователь
participant Интерфейс as "UI"
participant Система as "Сервер"
database "База данных"

Пользователь -> Интерфейс: Ввод сообщения
Интерфейс -> Система: POST /отправитьСообщение
alt Успешная аутентификация
    Система -> "База данных": Проверить существование чата
    "База данных" --> Система: Чат найден
    Система -> "База данных": Сохранить сообщение
    "База данных" --> Система: Успех сохранения
    Система -> "База данных": Сохранить уведомление в Outbox таблице
    "База данных" --> Система: Успех сохранения
    Система --> Интерфейс: Ответ: Сообщение отправлено
    Интерфейс --> Пользователь: Уведомление об отправке
else Ошибка
    alt Чат не найден
        Система --> Интерфейс: Ошибка: Чат не существует
    else Внутренняя ошибка сервера
        Система --> Интерфейс: Ошибка: Сообщение не отправлено
    end
    Интерфейс --> Пользователь: Уведомление об ошибке
end
@enduml